/**
 * 根據玩法位置顯示球號
 */
export const ballShowPosition = {
  FIRST_FIVE: 'FIRST_FIVE',
  FIRST_FOUR: 'FIRST_FOUR',
  FIRST_THREE: 'FIRST_THREE',
  FIRST_TWO: 'FIRST_TWO',
  LAST_FIVE: 'LAST_FIVE',
  LAST_FOUR: 'LAST_FOUR',
  LAST_THREE: 'LAST_THREE',
  LAST_TWO: 'LAST_TWO',
  LAST_ONE: 'LAST_ONE',
  FIRST_ONE_THREE: 'FIRST_ONE_THREE',
  FIRST_ONE_FOUR: 'FIRST_ONE_FOUR',
  FIRST_ONE_FIVE: 'FIRST_ONE_FIVE',
  FIRST_ONE_TEN: 'FIRST_ONE_TEN',
  FIRST_TWO_THREE: 'FIRST_TWO_THREE',
  FIRST_TWO_FOUR: 'FIRST_TWO_FOUR',
  FIRST_TWO_FIVE: 'FIRST_TWO_FIVE',
  FIRST_TWO_NINE: 'FIRST_TWO_NINE',
  FIRST_THREE_FOUR: 'FIRST_THREE_FOUR',
  FIRST_THREE_FIVE: 'FIRST_THREE_FIVE',
  FIRST_THREE_EIGHT: 'FIRST_THREE_EIGHT',
  FIRST_FOUR_SEVEN: 'FIRST_FOUR_SEVEN',
  FIRST_FIVE_SIX: 'FIRST_FIVE_SIX',
  FIRST_TWO_THREE_FOUR: 'FIRST_TWO_THREE_FOUR',
  ALL: 'ALL',
};
