/**
 * 根據玩法 球要顯示組態的位置
 */
export const ballShowPosition = {
  FIRST_FIVE: 'FIRST_FIVE', // 前五球
  FIRST_FOUR: 'FIRST_FOUR',
  FIRST_THREE: 'FIRST_THREE',
  FIRST_TWO: 'FIRST_TWO',
  FIRST_ONE: 'FIRST_ONE',
  LAST_FIVE: 'LAST_FIVE', // 後五球
  LAST_FOUR: 'LAST_FOUR',
  LAST_THREE: 'LAST_THREE',
  LAST_TWO: 'LAST_TWO',
  LAST_ONE: 'LAST_ONE',
  FIRST_ONE_THREE: 'FIRST_ONE_THREE', // 前一、三球
  FIRST_ONE_FOUR: 'FIRST_ONE_FOUR',
  FIRST_ONE_FIVE: 'FIRST_ONE_FIVE',
  FIRST_ONE_TEN: 'FIRST_ONE_TEN',
  FIRST_TWO_THREE: 'FIRST_TWO_THREE',
  FIRST_TWO_FOUR: 'FIRST_TWO_FOUR',
  FIRST_TWO_FIVE: 'FIRST_TWO_FIVE',
  FIRST_TWO_NINE: 'FIRST_TWO_NINE',
  FIRST_THREE_FOUR: 'FIRST_THREE_FOUR',
  FIRST_THREE_FIVE: 'FIRST_THREE_FIVE',
  FIRST_THREE_EIGHT: 'FIRST_THREE_EIGHT',
  FIRST_FOUR_SEVEN: 'FIRST_FOUR_SEVEN',
  FIRST_FIVE_SIX: 'FIRST_FIVE_SIX',
  FIRST_TWO_TO_FOUR: 'FIRST_TWO_TO_FOUR', // 前二到四球
  LAST_TWO_THREE: 'LAST_TWO_THREE', // 後二、三球
  ALL: 'ALL', // 所有球
};

export const ballConfigurationCategory = {
  CONFIGURATION_NUMBER: 'CONFIGURATION_NUMBER', // 組態數
  BALL_SUM: 'BALL_SUM', // 和值
  SPECIAL_NUMBER: 'SPECIAL_NUMBER', // 特殊號
  BALL_SPAN: 'BALL_SPAN', // 跨度
  SSC_BSOE: 'SSC_BSOE', // 時時彩 總和大小 總和單雙
  DRAGON_TIGER_TIE: 'DRAGON_TIGER_TIE', // 龍虎和
  EMPTY: 'EMPTY', // 不顯示組態
};
